version: 2
jobs:
  build:
    working_directory: ~/test
    docker:
      - image: circleci/node:6.10
    steps:
      - checkout
      - run:
          name: Show current branch
          command: echo ${CIRCLE_BRANCH}
          # Restore local dependencies from cache
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      # Install project dependencies
      - run:
          name: Install local dependencies
          command: npm install
      # Cache local dependencies if they don't exist
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
              - node_modules
      # test
      - run:
          name: Execute tests
          command: npm test

workflows:
  version: 2
  run-deployments:
    jobs:
      - build
